get http://localhost:3000/movies/

###
post http://localhost:3000/movies/
Content-Type: application/json

{
  "directorId": 6,
  "movieName": "Jurassic Park",
  "leadActor": "Jeff Goldblum"
}
###
get http://localhost:3000/movies/5/
